sudo: false

branches:
  only:
  - master

cache:
  npm: true
  directories:
    - node_modules

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - name: Build output
      language: node_js
      node_js: '10'
      before_script:
        - npm install
      script:
        - .travis/build-output.sh
